app:
  paging:
    defaultPageSize: "${DEFAULT_PAGE_SIZE}"
  kafka:
    bootstrapServers: "${KAFKA_BOOTSTRAP_SERVERS}"
    notificationsTopicName: "${NOTIFICATIONS_TOPIC}"
    createAssetPermissionsTopicName: "${CREATE_ASSET_PERMISSIONS_TOPIC}"
  auth:
    baseUrl: "${AUTH_BASEURL}"
    internal-user:
      username: "${INTERNAL_USERNAME}"
      password: "${INTERNAL_PASSWORD}"
  remoteServices:
    - id: "asset-service"
      baseUrl: "${ASSET_SERVICE_BASEURL}"
    - id: "notification-service"
      baseUrl: "${NOTIFICATION_SERVICE_BASEURL}"
spring:
  r2dbc:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  sql:
    init:
      mode: "${SQL_INIT_MODE}"
      schemaLocations:
        - "classpath:schema-create.sql"