app:
  paging:
    defaultPageSize: 10
  kafka:
    bootstrapServers: "localhost:9092"
    notificationsTopicName: "create_notifications"
    createAssetPermissionsTopicName: "asset_permissions"
  auth:
    baseUrl: "http://localhost:8000"
  remoteServices:
    - id: "asset-service"
      baseUrl: "http://localhost:8082"
    - id: "notification-service"
      baseUrl: "http://localhost:8000"
logging:
  level:
    com.github.sujankumarmitra.libraryservice: "DEBUG"
    io.r2dbc.postgresql.QUERY: "DEBUG"
    io.r2dbc.postgresql.PARAM: "DEBUG"
spring:
  devtools:
    livereload:
      enabled: false
  r2dbc:
    url: "r2dbc:postgres://localhost:5432/library_service_db"
    username: "library_service"
    password: "library_service"
  sql:
    init:
      mode: "ALWAYS"
      schemaLocations:
        - "classpath:schema-create.sql"