logging:
  level:
    com.github.sujankumarmitra.libraryservice: "DEBUG"
    io.r2dbc.postgresql.QUERY: "DEBUG"
    io.r2dbc.postgresql.PARAM: "DEBUG"
spring:
  r2dbc:
    url: "r2dbc:postgres://localhost:5432/library_service_db"
    username: "guest"
    password: "guest"
  sql:
    init:
      mode: "ALWAYS"
      schemaLocations:
        - "classpath:schema-create.sql"