app:
  job-scheduler:
    maxThreadCapacity: "${JOB_SCHEDULER_MAX_THREAD_CAPACITY}"
  auth:
    baseUrl: "${AUTH_BASEURL}"
  kafka:
    bootstrapServers: "${KAFKA_BOOTSTRAP_SERVERS}"
    newNotificationsTopicName: "${NEW_NOTIFICATIONS_TOPIC_NAME}"
    createNotificationsTopicName: "${CREATE_NOTIFICATIONS_TOPIC_NAME}"
spring:
  data:
    mongodb:
      uri: "${DB_URL}"