app:
  job-scheduler:
    maxThreadCapacity: "${JOB_SCHEDULER_MAX_THREAD_CAPACITY}"
  auth:
    baseUrl: "${AUTH_SERVER_URL}"
  kafka:
    bootstrapServers: "${KAFKA_BOOTSTRAP_SERVERS}"
spring:
  data:
    mongodb:
      uri: "${DB_URL}"