app:
  auth:
    baseUrl: "${AUTH_SERVER_URL:http://localhost:5000}"
  kafka:
    bootstrapServers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
    newNotificationsTopicName: "${KAFKA_NEW_NOTIFICATION_TOPIC_NAME:new_notifications}"
    createNotificationsTopicName: "${KAFKA_CREATE_NOTIFICATION_TOPIC_NAME:create_notifications}"
spring:
  data:
    mongodb:
      uri: "${DB_URL:mongodb://localhost:27017/notification_service}"