server:
  port: 8083
app:
  job-scheduler:
    maxThreadCapacity: 50
  auth:
    baseUrl: "http://localhost:8000"
    internal-user:
      username: "username"
      password: "password"
  kafka:
    bootstrapServers: "localhost:9092"
    newNotificationsTopicName: "new_notifications"
    createNotificationsTopicName: "create_notifications"
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/notification_service_db"