server:
  port: 8083
app:
  job-scheduler:
    maxThreadCapacity: 50
  auth:
    baseUrl: "http://localhost:8000"
  kafka:
    bootstrapServers: "localhost:9092"
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/notification_service"