version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "library_service"
      POSTGRES_USER: "library_service"
      POSTGRES_DB: "library_service_db"
  pgadmin:
    image: "dpage/pgadmin4"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin_user@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin_password"
    ports:
      - "5433:80"
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
    depends_on:
    - zookeeper
  control-center:
    image: confluentinc/cp-enterprise-control-center
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:19092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
  app:
    image: library-service:1.0.0
    depends_on:
      - kafka
      - db
    ports:
      - "8080:8080"
    environment:
      DEFAULT_PAGE_SIZE: "10"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
      NOTIFICATIONS_TOPIC: "new_notifications"
      CREATE_ASSET_PERMISSIONS_TOPIC: "create_asset_permissions"
      ASSET_SERVICE_BASEURL: "http://172.17.0.1:8082"
      AUTH_BASEURL: "http://172.17.0.1:8000"
      DB_URL: "r2dbc:postgresql://db/library_service_db"
      DB_USERNAME: "library_service"
      DB_PASSWORD: "library_service"
      SQL_INIT_MODE: "ALWAYS"

