version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "library_service"
      POSTGRES_USER: "library_service"
      POSTGRES_DB: "library_service_db"
  pgadmin:
    image: "dpage/pgadmin4"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin_user@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin_password"
    ports:
      - "5433:80"
  app:
    image: library-service:1.0.0
    depends_on:
      - kafka
      - db
    ports:
      - "8080:8080"
    environment:
      DEFAULT_PAGE_SIZE: "10"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
      NOTIFICATIONS_TOPIC: "new_notifications"
      CREATE_ASSET_PERMISSIONS_TOPIC: "create_asset_permissions"
      ASSET_SERVICE_BASEURL: "http://172.17.0.1:8082"
      AUTH_BASEURL: "http://172.17.0.1:8000"
      DB_URL: "r2dbc:postgresql://db/library_service_db"
      DB_USERNAME: "library_service"
      DB_PASSWORD: "library_service"
      SQL_INIT_MODE: "ALWAYS"

