version: "2"
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTRES_DB: "db"
    volumes:
      - "./initdb/:/docker-entrypoint-initdb.d/"
      - "./asset-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/scripts/asset_service_db.sql"
      - "./library-service/src/main/resources/schema-create.sql:/docker-entrypoint-initdb.d/scripts/library_service_db.sql"
    mem_limit: "100m"
  mongo:
    image: "mongo"
    mem_limit: "100m"
  redis:
    image: "redis"
    mem_limit: "50m"
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    mem_limit: "100m"
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: localhost
    depends_on:
      - zookeeper
    mem_limit: "500m"
  asset-service:
    image: "asset-service:1.0.0"
    depends_on:
      - postgres
      - e-learning-system-api
    ports:
      - "7002:8080"
    environment:
      STORAGE_BASEDIR: "/tmp"
      AUTH_BASEURL: "http://e-learning-system-api:3699/api/auth"
      DB_URL: "r2dbc:postgresql://postgres:5432/asset_service_db"
      DB_USERNAME: "asset_service"
      DB_PASSWORD: "asset_service"
      SQL_INIT_MODE: "NEVER"
    mem_limit: "300m"
  notification-service:
    image: "notification-service:1.0.0"
    ports:
      - "7003:8080"
    depends_on:
      - mongo
      - kafka
      - e-learning-system-api
    environment:
      JOB_SCHEDULER_MAX_THREAD_CAPACITY: "50"
      AUTH_BASEURL: "http://e-learning-system-api:3699/api/auth"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
      NEW_NOTIFICATIONS_TOPIC_NAME: "new_notifications"
      CREATE_NOTIFICATIONS_TOPIC_NAME: "create_notifications"
      DB_URL: "mongodb://mongo:27017/notification_service_db"
    mem_limit: "300m"
  library-service:
    image: library-service:1.0.0
    depends_on:
      - kafka
      - postgres
      - e-learning-system-api
      - asset-service
    ports:
      - "7004:8080"
    environment:
      DEFAULT_PAGE_SIZE: "10"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
      NOTIFICATIONS_TOPIC: "create_notifications"
      CREATE_ASSET_PERMISSIONS_TOPIC: "create_asset_permissions"
      AUTH_BASEURL: "http://e-learning-system-api:3699/api/auth"
      ASSET_SERVICE_BASEURL: "http://asset-service:8080"
      DB_URL: "r2dbc:postgresql://postgres:5432/library_service_db"
      DB_USERNAME: "library_service"
      DB_PASSWORD: "library_service"
      SQL_INIT_MODE: "NEVER"
    mem_limit: "300m"
  ebook-processor:
    image: ebook-processor:1.0.0
    depends_on:
      - redis
      - e-learning-system-api
      - asset-service
      - library-service
    ports:
      - "7005:8080"
    environment:
      REDIS_URL: "redis://redis:6379"
      REDIS_KEY_EXPIRY_IN_MILLISECONDS: "3600000"
      REDIS_PASSWORD: ""
      LIBRARY_SERVICE_BASEURL: "http://library-service:8080"
      ASSET_SERVICE_BASEURL: "http://asset-service:8080"
      AUTH_BASEURL: "http://e-learning-system-api:3699/api/auth"
    mem_limit: "300m"
  e-learning-system-api:
    image: e-learning-system-api
    volumes:
      - "./.env:/app/.env"
    build:
      context: .
      dockerfile: e-learning-system-api/Dockerfile
    ports:
      - '3699:3699'
    mem_limit: "100m"
  react-frontend:
    image: csuvajit/react-frontend:latest
    volumes:
      - "./.env:/app/.env"
    ports:
      - '3000:3000'
    depends_on:
      - e-learning-system-api
    mem_limit: "100m"
