version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "asset_service"
      POSTGRES_USER: "asset_service"
      POSTGRES_DB: "asset_service_db"
    ports:
      - "5432:5432"
