version: "3"
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "asset_service"
      POSTGRES_USER: "asset_service"
      POSTGRES_DB: "asset_service_db"
    ports:
      - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "pgadmin"
    depends_on:
      - db
    volumes:
      - "/home/skmitra/Docker/volumes/pgadmin:/var/lib/pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin_user@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin_password"
    ports:
      - "5433:80"
  app:
    image: "asset-service:1.0.0"
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      STORAGE_BASEDIR: "/tmp"
      AUTH_BASEURL: "http://172.17.0.1:8000"
      DB_URL: "r2dbc:postgresql://db/asset_service_db"
      DB_USERNAME: "asset_service"
      DB_PASSWORD: "asset_service"
      SQL_INIT_MODE: "ALWAYS"