spring:
  redis:
    url: "${REDIS_URL}"
    password: "${REDIS_PASSWORD}"
app:
  ebookProcessor:
    threadPoolCapacity: 50
    maxSegmentSize: 10
  redis:
    password: "${spring.redis.password}"
    defaultKeyExpirationInMilliseconds: 3600000
  remoteServices:
    - id: "library-service"
      baseUrl: "${LIBRARY_SERVICE_BASEURL}"
    - id: "asset-service"
      baseUrl: "${ASSET_SERVICE_BASEURL}"
  auth:
    baseUrl: "${AUTH_BASEURL}"
