server:
  port: 8081
logging:
  level:
    com.github.sujankumarmitra.ebookprocessor: "DEBUG"
spring:
  redis:
    url: "redis://localhost:6379"
    password: ""
app:
  ebookProcessor:
    threadPoolCapacity: 20
    maxSegmentSize: 10
  redis:
    url: "${spring.redis.url}"
    password: "${spring.redis.password}"
    defaultKeyExpirationInMilliseconds: 3600000
  remoteServices:
    - id: "library-service"
      baseUrl: "http://localhost:8082"
    - id: "asset-service"
      baseUrl: "http://localhost:8080"
  auth:
    baseUrl: "http://localhost:8000"
