app:
  storage:
    baseDir: "${STORAGE_BASEDIR}"
  auth:
    baseUrl: "${AUTH_BASEURL}"
spring:
  r2dbc:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  sql:
    init:
      mode: "${SQL_INIT_MODE}"