app:
  storage:
    baseDir: "${STORAGE_DIR:/tmp}"
  auth:
    baseUrl: "${AUTH_SERVER_URL:http://localhost:5000}"
spring:
  data:
    mongodb:
      uri: "${DB_URL:mongodb://localhost:27017/asset_service}"