app:
  storage:
    baseDir: "/tmp"
  auth:
    baseUrl: "http://localhost:8000"
spring:
  r2dbc:
    url: "r2dbc:postgres://localhost:5432/asset_service_db"
    username: "asset_service"
    password: "asset_service"
  sql:
    init:
      mode: "ALWAYS"